name: Deploy

# Trigger the workflow on push and pull request events on the UAT branch
on:
  push:
    branches:
      - madhav

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/madhav.ready2pay.in/hangout && ./.scripts/deploy.sh"
