name: Deploy

# Trigger the workflow on push and pull request events on the UAT branch
on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory /var/www/madhav.ready2pay.in/hangout

      - name: Push Changes
        run: |
          cd /var/www/madhav.ready2pay.in/hangout
          git add .
          git commit -m "Deploy changes" || echo "No changes to commit"
          git push origin madhav
