name: Deploy

# Trigger the workflow on push events on the UAT branch
on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/madhav.ready2pay.in/hangout
            git config --global --add safe.directory /var/www/madhav.ready2pay.in/hangout  # Add the directory as a safe directory
            git pull origin UAT  # Pull the latest changes from UAT
            chmod +x ./.scripts/deploy.sh  # Ensure your deploy script is executable
            ./.scripts/deploy.sh  # Run your deployment script
